language: python
python: "3.9"
sudo: false

#branches:
#  except:
#  - main

env:
  global:
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH


# command to install dependencies
install:
  - pip install -r requirements-travis.txt

# command to run tests
script:
  - python deploy_pipeline.py

