language: python
python: "3.9"
sudo: false


env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH


# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - aws sts get-caller-identity

